/**
 * Unified dataSourcesInfo — merges Dataverse tables + Flow connectors.
 * SDK getClient() is a singleton; all data sources must be included in a single info object.
 * .power/schemas/appschemas/dataSourcesInfo.ts is auto-generated by SDK and may be overwritten.
 * Custom entries (systemusers, flow connectors) are added here to survive regeneration.
 */
import { dataSourcesInfo as powerInfo } from "../../.power/schemas/appschemas/dataSourcesInfo";

export const dataSourcesInfo = {
  ...powerInfo,
  systemusers: {
    tableId: "systemuser",
    version: "",
    primaryKey: "systemuserid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  geek_incidents: {
    tableId: "geek_incident",
    version: "",
    primaryKey: "geek_incidentid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  geek_workers: {
    tableId: "geek_worker",
    version: "",
    primaryKey: "geek_workerid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  geek_checklistitems: {
    tableId: "geek_checklistitem",
    version: "",
    primaryKey: "geek_checklistitemid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  GenerateSalesEmail: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
          { name: "text_2", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          airesult: { type: "string" },
        },
      },
    },
  },
  SuggestAppointment: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          airesult: { type: "string" },
        },
      },
    },
  },
  GetOutlookEvents: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          events_json: { type: "string" },
        },
      },
    },
  },
};
